# Generated by Django 3.0.5 on 2020-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
