# Generated by Django 3.0.5 on 2020-04-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='dash video link', max_length=200),
        ),
    ]
